### ISSUE TITLE
Have you ever tried STFT as encoder input?

### ISSUE THREAD

**Issue by casioexlim** [hertz-pj/SNAC-Vocos#3]
First of all ,thank you for your great work,  SNACK-Vocos works well on  Emilia dataset.
I found that SEANet 's computation complexity is pretty vast because of RAW waveform as input.

Have you ever tried  STFT as SEANet's  input, which will reduce time sequence's length by hopsize times.

If you did that, what is your experienment ruslts?

I will be looking forward to your reply.

**Comment by hertz-pj** [comment]
I have tried using STFT as SEANet's input, however, the results were not as good as using raw waveform directly as input.

**Comment by casioexlim** [comment]
Thank you for your reply.
by the way,
Could you discribe the difference between STFT and  raw waveform by Mos score or pesq?
